name: halueval_qa
path: data/HaluEval/qa_data.json
cls_path: src.data.halueval.HaluEvalQADataset

# DVC pipeline fields
split_name: train
task_type: null

splits: null
task_types: null
max_samples: null

max_answer_tokens: 256
target_column_name: hallucinated_answer
test_split_name: null